import 'dart:math';

class Frasi {
  static Map<String, List<String>> tutte = {
    'italiano': [
      "La mattina è quasi finita. Tu dove sei stato?",
      "Sono passate tre ore. E tu non lo sai.",
      "Metà giornata è già andata. Non sai nemmeno come.",
      "Stai aspettando qualcosa. Non arriverà da solo.",
      "Ogni ora che passa non esiste più.",
      "Hai rimandato ancora. Hai rimandato anche di vivere.",
      "Mentre decidi, il tempo continua a passare.",
      "Questa sera guarderai indietro. Cosa vedrai?",
      "Non c'è una versione futura di te che sistemerà tutto.",
      "Stai vivendo o stai solo aspettando di farlo?",
      "Quante volte hai detto domani?",
      "Il tuo telefono sa tutto di te. Anche quanto tempo sprechi.",
      "Stai invecchiando anche adesso, mentre leggi questa notifica.",
      "L’esperienza non è quanti cibi diversi hai mangiato, ma quanto hai davvero assaporato qualcosa.",
      "La vita non è in pausa. Solo tu lo sei.",
      "Hai aperto questa app. Ora svegliati.",
      "Nessuno ti restituirà questo pomeriggio.",
      "Stai aspettando di sentirti pronto. Non succederà, perché sei già pronto.",
      "Oggi finirà. Come tutti gli altri giorni in cui non ti sei ascoltato.",
      "Prendi così tanta rincorsa che quando devi partire sei stanco morto. O solo morto.",
      "Hai controllato il telefono 47 volte oggi. Niente di importante.",
      "La tua lista di cose da fare è più vecchia dei tuoi sogni.",
      "Stai aspettando l'umore giusto. Non è una strategia.",
      "Ogni notifica che hai aperto oggi valeva il tuo tempo?",
      "Passi più di un terzo dell’anno dormendo. Sei più attivo quando dormi di quando pensi di essere sveglio.",
      "Il tuo corpo invecchia anche quando non fai nulla.",
      "Hai rimandato così tanto che hai dimenticato cosa volevi.",
      "Non è pigrizia. È paura. Ed è peggio.",
      "Tra dieci anni ricorderai questo momento come tempo perso.",
      "Stai leggendo questo messaggio invece di fare quella cosa, proprio quella cosa. Lo sai.",
      "Hai un sogno nel cassetto. Il cassetto è chiuso da anni.",
      "Non stai riposando. Stai solo rimandando in posizione orizzontale.",
      "Oggi hai detto: “Dopo lo faccio”. Quel dopo è passato da un pezzo.",
      "Il tempo che hai sprecato oggi non tornerà nemmeno se lo chiedi gentilmente.",
      "Stai aspettando che qualcuno ti dia il permesso. Non arriverà.",
      "Hai così tanto pensato a cosa fare che adesso che stai per farlo hai cambiato idea.",
      "La giornata sta finendo. Come tutte le altre.",
      "Il tuo potenziale è stanco di aspettarti.",
      "Ogni giorno è uguale a quello precedente perché continui a sperare che il destino si occupi di te senza di te.",
      "Ti consumi da solo, senza considerare l’alternativa: consumare tu la vita.",
      "Ogni giorno uguale al precedente è una scelta.",
      "Che triste la versione di te tra 5 anni che si aspettava grandi cose. Ma tu non ti sei svegliato.",
      "Svegliati e impara ad ascoltare chi ti parla invece di pensare che dovresti.",
      "Stai aspettando la motivazione. È lei che aspetta te.",
      "Hai vissuto oggi o l'hai solo attraversato?",
      "Il problema non è il tempo, ma la sua profondità.",
      "Domani inizierà esattamente come oggi. A meno che tu non faccia qualcosa adesso.",
      "Stai collezionando tantissime idee che non metti in pratica. Collezioni i sogni degli altri.",
      "La tua vita non è in costruzione. È in corso. Adesso.",
      "Hai così paura del tempo che passa che preferisci allontanarlo da te.",
      "Driiiiiiinnnnnn. Sveglia, che stai ancora dormendo.",
      "La vita è esattamente ora.",
      "Hai un sogno. Hai solo dimenticato dove l'hai messo.",
      "Stai scrollando. La tua vita scrolla via.",
      "Non hai rimandato una cosa. Hai rimandato te stesso.",
      "Sei ancora lì dove eri ieri. Non è un caso.",
      "Hai bisogno di una pausa da cosa, esattamente?",
      "Stai costruendo tutte le condizioni per essere felice in futuro. Sempre che ci si arrivi, a questo incredibile futuro.",
      "Non ricorderai questo momento. È questo il problema.",
      "Hai così tanta vita, ma la cerchi davanti.",
      "Il silenzio che senti è il tempo che passa.",
      "Non è stanchezza. È distanza da te stesso.",
      "Stai vivendo per abitudine o per scelta?",
      "Oggi hai fatto qualcosa per la prima volta?",
      "Non è troppo tardi, ma non è neanche presto.",
      "Mentre aspetti il momento perfetto che è sempre futuro, il momento perfetto se ne sbatte e si prende un aperitivo senza te.",
      "Hai paura di iniziare o di finire?",
      "Non è che non sai cosa fare. È che sai cosa non stai facendo.",
      "Quante versioni di te hai abbandonato per strada?",
      "Non esiste il giorno giusto. Esiste solo questo.",
      "Stai aspettando di sentirti meglio. Il corpo non mente, la mente sì.",
      "Hai controllato bene i social, che nulla sia cambiato rispetto a qualche minuto fa?",
      "Stai costruendo qualcosa o stai solo guardando gli altri costruire?",
      "Ogni minuto che passa è un minuto che hai scelto.",
      "Non è colpa di nessuno. È più difficile da accettare così.",
      "Stai invecchiando in tempo reale. Anche adesso.",
      "A furia di rimandare, tu sei diventata la persona che rimanda.",
      "Non ti serve più tempo. Ti serve meno paura.",
      "Stai aspettando che qualcosa cambi. Sei tu quella cosa.",
      "Oggi hai fatto qualcosa che avevi paura di fare?",
      "Il tuo futuro ti sta guardando. Non sembra soddisfatto.",
      "Non è una fase. Sono anni.",
      "Stai consumando la tua vita guardando quella degli altri.",
      "Non hai perso il tempo. Hai perso te stesso nel tempo.",
      "Sei sveglio. Non è la stessa cosa di essere presente.",
      "Hai tutto quello che ti serve. Tranne il coraggio di usarlo.",
      "Stai aspettando il permesso. Non arriverà per posta.",
      "Non è che non puoi. È che non hai ancora deciso di volere.",
      "Oggi finirà. Cosa dirai che hai fatto?",
      "Non stai riposando. Stai evitando.",
      "Avevi una vita davanti. Ora ne hai meno. Domani ancora meno. Non sei eterno.",
      "Le ali te le fai volando.",
      "Sei così avaro di vita che pure la noia preferisce distrarsi.",
      "Pigro d’amore per te stesso.",
      "Non è troppo tardi per oggi. Ma oggi sta finendo.",
      "Non stai cercando il senso. Stai cercando una scusa.",
      "Sei ancora qui. È già qualcosa. Ma non basta.",
      "Hai tutto quello che ti serve tranne una ragione per non iniziare adesso.",
      "Meglio crogiolarsi nei sogni che non hai provato a realizzare che rischiare di scoprire che non erano i tuoi.",
      "FINITO.",
    ],
    'english': [
      "The morning is almost over. Where have you been?",
      "Three hours have passed. And you didn't notice.",
      "Half the day is already gone. You don't even know how.",
      "You're waiting for something. It won't come on its own.",
      "Every hour that passes no longer exists.",
      "You postponed again. You postponed living too.",
      "While you decide, time keeps moving.",
      "Tonight you'll look back. What will you see?",
      "There is no future version of you that will fix everything.",
      "Are you living, or just waiting to do it?",
      "How many times have you said tomorrow?",
      "Your phone knows everything about you. Including how much time you waste.",
      "You're aging even now, while you read this notification.",
      "Experience isn't about how many different foods you've eaten, but how deeply you've truly savored something.",
      "Life is not on pause. Only you are.",
      "You opened this app. Now wake up.",
      "No one will give you this afternoon back.",
      "You're waiting to feel ready. It won't happen, because you already are.",
      "Today will end. Like all the other days when you didn't listen to yourself.",
      "You take such a long run-up that by the time you're ready to go, you're already dead tired. Or just dead.",
      "You checked your phone 47 times today. Nothing important.",
      "Your to-do list is older than your dreams.",
      "You're waiting for the right mood. That's not a strategy.",
      "Was every notification you opened today worth your time?",
      "You spend more than a third of the year asleep. You're more active while sleeping than when you think you're awake.",
      "Your body ages even when you do nothing.",
      "You've postponed so much you forgot what you wanted.",
      "It's not laziness. It's fear. And that's worse.",
      "In ten years you'll remember this moment as wasted time.",
      "You're reading this message instead of doing that thing, that very thing. You know it.",
      "You have a dream in a drawer. The drawer has been closed for years.",
      "You're not resting. You're just postponing horizontally.",
      "Today you said, “I'll do it later.” That later is long gone.",
      "The time you wasted today won't come back even if you ask nicely.",
      "You're waiting for someone to give you permission. It won't come.",
      "You thought about it so long that now you're about to do it, you've changed your mind.",
      "The day is ending. Like all the others.",
      "Your potential is tired of waiting for you.",
      "Every day is the same as the one before because you keep hoping fate will take care of you without you.",
      "You wear yourself out without considering the alternative: devouring life yourself.",
      "Every day the same as the previous one is a choice.",
      "How sad the version of you in 5 years that expected great things. But you never woke up.",
      "Wake up and learn to listen to those who speak to you instead of thinking you should.",
      "You're waiting for motivation. It's waiting for you.",
      "Did you live today or just pass through it?",
      "The problem isn't time, but its depth.",
      "Tomorrow will start exactly like today. Unless you do something now.",
      "You're collecting countless ideas you never put into practice. You're collecting other people's dreams.",
      "Your life is not under construction. It's happening. Right now.",
      "You're so afraid of time passing that you'd rather push it away from you.",
      "Riiiiiiing. Wake up, you're still sleeping.",
      "Life is exactly now.",
      "You have a dream. You just forgot where you put it.",
      "You're scrolling. Your life scrolls away.",
      "You didn't postpone a thing. You postponed yourself.",
      "You're still where you were yesterday. That's not a coincidence.",
      "You need a break from what, exactly?",
      "You're creating every condition for being happy in the future. Assuming you ever reach this incredible future.",
      "You won't remember this moment. That's the problem.",
      "You have so much life, yet you keep looking for it ahead of you.",
      "The silence you hear is time passing.",
      "It's not tiredness. It's distance from yourself.",
      "Are you living by habit or by choice?",
      "Did you do something for the first time today?",
      "It's not too late, but it isn't early either.",
      "While you wait for the perfect moment that is always in the future, the perfect moment doesn't care and goes for a drink without you.",
      "Are you afraid to start or to finish?",
      "It's not that you don't know what to do. It's that you know what you're not doing.",
      "How many versions of yourself have you left behind?",
      "There is no right day. There is only this one.",
      "You're waiting to feel better. The body doesn't lie, the mind does.",
      "Did you check social media carefully, to make sure nothing has changed since a few minutes ago?",
      "Are you building something or just watching others build?",
      "Every minute that passes is a minute you chose.",
      "It's nobody's fault. That's harder to accept.",
      "You're aging in real time. Even now.",
      "By putting things off over and over, you've become the person who puts things off.",
      "You don't need more time. You need less fear.",
      "You're waiting for something to change. You are that something.",
      "Did you do something today that you were afraid to do?",
      "Your future is watching you. It doesn't look satisfied.",
      "It's not a phase. It's been years.",
      "You're consuming your life watching everyone else's.",
      "You didn't lose time. You lost yourself in time.",
      "You're awake. That's not the same as being present.",
      "You have everything you need. Except the courage to use it.",
      "You're waiting for permission. It won't arrive by post.",
      "It's not that you can't. It's that you haven't decided you want to yet.",
      "Today will end. What will you say you did?",
      "You're not resting. You're avoiding.",
      "You had a whole life ahead of you. Now you have less. Tomorrow, even less. You are not eternal.",
      "You make your wings by flying.",
      "You're so stingy with life that even boredom prefers to distract itself.",
      "Too lazy to love yourself.",
      "It's not too late for today. But today is ending.",
      "You're not looking for meaning. You're looking for an excuse.",
      "You're still here. That's something. But it's not enough.",
      "You have everything you need except a reason not to start right now.",
      "Better to bask in the dreams you never tried to realize than risk discovering they weren't yours.",
      "FINITO.",
    ],
    'zhongwen': [
      "早晨快结束了。你在哪里？",
      "三个小时过去了。你不知道。",
      "半天已经消失了。你不知道怎么发生的。",
      "你在等待什么。它不会自己来。",
      "每一个过去的小时都不再存在。",
      "你又推迟了。你也推迟了活着。",
      "当你犹豫时，时间继续流逝。",
      "今晚你会回头看。你会看到什么？",
      "没有未来的你会修复一切。",
      "你是在生活，还是只是在等待去生活？",
      "你说了多少次明天？",
      "你的手机了解你的一切。包括你浪费了多少时间。",
      "你正在变老——就在阅读这条通知的此刻。",
      "经历不在于你吃过多少种不同的食物，而在于你是否真正品味过什么。",
      "生活没有暂停。只有你暂停了。",
      "你打开了这个应用。现在，醒过来。",
      "没有人会把这个下午还给你。",
      "你在等自己准备好。那一刻不会来，因为你早已准备好了。",
      "今天会结束。就像那些你从未倾听自己心声的日子一样。",
      "你助跑那么长，到要出发时已经累死了。或者只是死了。",
      "你今天检查了47次手机。没有任何重要的事。",
      "你的待办清单比你的梦想更古老。",
      "你在等待合适的心情。这不是策略。",
      "你今天打开的每条通知都值得你的时间吗？",
      "一年里，你有超过三分之一的时间在睡觉。你睡着时，反而比自以为清醒时更有活力。",
      "你的身体即使在你什么都不做的时候也在老去。",
      "你推迟了太多，以至于忘记了自己想要什么。",
      "不是懒惰。是恐惧。这更糟糕。",
      "十年后你会记得这一刻是浪费的时间。",
      "你在读这条消息，而不是去做那件事——就是那件事。你知道。",
      "你有一个梦想放在抽屉里。抽屉已经关了好几年了。",
      "你不是在休息。你只是在水平位置上推迟。",
      "今天你说：“以后再做。”那个“以后”早就过去了。",
      "你今天浪费的时间不会回来。",
      "你在等待某人给你许可。不会来的。",
      "你想了那么久该做什么，现在要做了，你又改变主意了。",
      "这一天要结束了。就像所有其他的一样。",
      "你的潜力已经厌倦了等你。",
      "每一天都和前一天一样，因为你一直指望命运撇开你，独自替你安排人生。",
      "你独自耗损自己，却没想过另一种可能：由你去尽情消耗生命。",
      "每天和前一天一样是一种选择。",
      "多么悲哀，五年后的你期待着伟大的事情。但你从未醒来。",
      "醒来，学会倾听和你说话的人。",
      "你在等待动力。它在等你。",
      "你今天是活着还是只是经过？",
      "问题不在时间，而在时间的深度。",
      "明天会和今天一样开始。除非你现在做些什么。",
      "你收集了无数从未付诸行动的想法。你收集的是别人的梦想。",
      "你的生活不是在建设中。它正在发生。就在现在。",
      "你如此害怕时间流逝，宁愿把它从自己身边推开。",
      "叮铃铃！醒醒，你还在睡觉。",
      "生命，就是此时此刻。",
      "你有一个梦想。你只是忘了放在哪里。",
      "你在刷屏。你的生命也随之滑走。",
      "你没有推迟一件事。你推迟了你自己。",
      "你还在昨天的地方。这不是巧合。",
      "你需要从什么中休息？",
      "你正在为未来的幸福创造一切条件——前提是你真能抵达那个不可思议的未来。",
      "你不会记得这一刻。这就是问题所在。",
      "你拥有如此丰盛的生命，却总在前方寻找它。",
      "你听到的沉默是时间流逝的声音。",
      "不是疲惫。是与自己的距离。",
      "你是出于习惯还是出于选择而活着？",
      "今天你做了第一次的事情吗？",
      "还不算太晚，但也已经不早了。",
      "当你等待完美时刻时，完美时刻不在乎，自己去喝酒了，没有你。",
      "你害怕开始还是结束？",
      "不是你不知道该做什么。是你知道你没在做什么。",
      "你在路上抛弃了多少个版本的自己？",
      "没有正确的日子。只有这一天。",
      "你在等感觉好一点。身体不说谎，心智会。",
      "你仔细检查社交媒体了吗，确认和几分钟前相比什么都没变？",
      "你在建造什么，还是只是看别人建造？",
      "每一分钟的流逝都是你选择的。",
      "不是任何人的错。这样更难接受。",
      "你在实时老去。就在现在。",
      "一次次拖延之后，你已经成了那个总在拖延的人。",
      "你不需要更多时间。你需要更少的恐惧。",
      "你在等待某些事情改变。你就是那件事。",
      "今天，你做了那件你害怕去做的事吗？",
      "你的未来在看着你。它看起来不满意。",
      "不是一个阶段。已经是好几年了。",
      "你在看别人的生活中消耗自己的生活。",
      "你没有失去时间。你在时间中失去了自己。",
      "你醒着。这和存在于当下不是一回事。",
      "你拥有你需要的一切。除了使用它的勇气。",
      "你在等待许可。它不会邮寄来的。",
      "不是你不能。是你还没决定你想要。",
      "今天会结束。你会说你做了什么？",
      "你不是在休息。你在逃避。",
      "你曾有整个人生在前方。如今少了一些，明天还会更少。你并非永恒。",
      "翅膀，是在飞翔中长出来的。",
      "你如此吝啬生命，连无聊都宁愿分心。",
      "你懒得去爱自己。",
      "今天还没太晚。但今天要结束了。",
      "你不是在寻找意义。你在寻找借口。",
      "你还在这里。这已经是什么了。但还不够。",
      "你拥有一切你需要的，除了不立刻开始的理由。",
      "宁愿沉醉于那些从未尝试实现的梦想，也不愿冒险发现它们原来并不属于你。",
      "结束了。",
    ],
    'nihongo': [
      "朝がもう終わりそうだ。あなたはどこにいたの？",
      "三時間が過ぎた。あなたは気づかなかった。",
      "半日がもう消えた。どうやってそうなったかわからない。",
      "何かを待っている。それは自分では来ない。",
      "過ぎ去った時間はもう存在しない。",
      "またも先延ばしにした。生きることも先延ばしにした。",
      "迷っている間も、時間は流れ続ける。",
      "今夜、振り返るだろう。何が見える？",
      "すべてを修正してくれる未来の自分など存在しない。",
      "生きているのか、それとも生きることをただ待っているのか？",
      "「明日」と何回言った？",
      "あなたのスマホはあなたのすべてを知っている。どれだけ時間を無駄にしているかも。",
      "この通知を読んでいる今この瞬間にも、あなたは老いている。",
      "経験とは、何種類の料理を食べたかではない。何かを本当に味わったかどうかだ。",
      "人生は一時停止していない。あなただけが止まっている。",
      "このアプリを開いた。さあ、目を覚ませ。",
      "この午後をあなたに返してくれる人はいない。",
      "準備ができたと感じるのを待っている。その時は来ない。もう準備はできているからだ。",
      "今日も終わる。自分の声を聞かなかった、ほかのすべての日と同じように。",
      "助走をとりすぎて、いざ出発しようとしたら疲れ果てていた。あるいはただ死んでいた。",
      "今日スマホを47回チェックした。大事なことは何もなかった。",
      "あなたのやることリストは夢より古い。",
      "正しい気分を待っている。それは戦略ではない。",
      "今日開いた通知は、あなたの時間に値するものだったか？",
      "一年の三分の一以上を眠って過ごす。眠っているときのほうが、目覚めているつもりのときより活発だ。",
      "何もしていなくても、体は老いていく。",
      "先延ばしにしすぎて、何が欲しかったか忘れてしまった。",
      "怠惰じゃない。恐怖だ。それの方がもっと悪い。",
      "十年後、この瞬間を無駄な時間として思い出すだろう。",
      "あのこと、まさにあのことをする代わりに、このメッセージを読んでいる。わかっているだろう。",
      "夢は引き出しの中にある。引き出しは何年も閉まったままだ。",
      "休んでいるのではない。ただ横になって先延ばしにしているだけだ。",
      "今日、「後でやる」と言った。その「後で」は、とうに過ぎ去った。",
      "今日無駄にした時間は戻ってこない。",
      "誰かが許可を与えてくれるのを待っている。来ない。",
      "何をするか考えすぎて、いざやろうとしたら気が変わった。",
      "この日も終わる。他のすべての日と同じように。",
      "あなたの可能性は、あなたを待つのに疲れた。",
      "運命があなた抜きであなたの面倒を見てくれると願い続けるから、毎日が前の日と同じになる。",
      "自分をすり減らしている。自分の手で人生を味わい尽くすという選択肢も考えずに。",
      "毎日前の日と同じというのは、選択だ。",
      "五年後のあなたが大きなことを期待していたなんて、なんと悲しい。でもあなたは目覚めなかった。",
      "目覚めて、話しかけてくれる人の声を聞くことを学べ。",
      "やる気を待っている。やる気があなたを待っている。",
      "今日は生きたか、それともただ通り過ぎただけか？",
      "問題は時間ではない。その深さだ。",
      "明日も今日と同じように始まる。今何かしない限り。",
      "実行しないアイデアばかりを集めている。集めているのは他人の夢だ。",
      "あなたの人生は建設中ではない。今まさに起きている。",
      "過ぎていく時間が怖すぎて、自分から遠ざけようとしている。",
      "リリリリン！起きて、まだ寝ている。",
      "人生とは、まさに今だ。",
      "夢がある。どこに置いたか忘れただけだ。",
      "スクロールしている。あなたの人生も流れ去っていく。",
      "何かを先延ばしにしたのではない。自分自身を先延ばしにした。",
      "昨日と同じ場所にいる。偶然ではない。",
      "一体何から休憩が必要なのか？",
      "未来に幸せになるための条件をすべて整えている。もっとも、その途方もない未来にたどり着ければの話だ。",
      "この瞬間を覚えていないだろう。それが問題だ。",
      "これほど多くの命を持ちながら、それをいつも前方に探している。",
      "聞こえる沈黙は、時間が過ぎていく音だ。",
      "疲れではない。自分自身からの距離だ。",
      "習慣で生きているのか、選択で生きているのか？",
      "今日、初めてのことをしたか？",
      "遅すぎはしない。だが、もう早くもない。",
      "完璧な瞬間を待っている間に、完璧な瞬間はどうでもよくなって、あなたなしで一杯飲みに行った。",
      "始めることが怖いのか、終わることが怖いのか？",
      "何をすべきかわからないのではない。何をしていないかわかっているのだ。",
      "道中、何人の自分を置き去りにしてきた？",
      "正しい日などない。あるのはこの日だけだ。",
      "良くなるのを待っている。体は嘘をつかない、心はつく。",
      "数分前から何も変わっていないか、SNSをちゃんと確認したか？",
      "何かを作っているのか、それともただ他人が作るのを見ているのか？",
      "過ぎ去る一分一分は、あなたが選んだ一分だ。",
      "誰のせいでもない。そう認めるのがもっと難しい。",
      "今この瞬間も、リアルタイムで老いていく。",
      "先延ばしを重ねるうちに、あなたは「先延ばしにする人」になった。",
      "もっと時間が必要なのではない。必要なのは、恐れを減らすことだ。",
      "何かが変わるのを待っている。あなたがその何かだ。",
      "今日、怖くてできなかったことをやったか？",
      "未来のあなたがあなたを見ている。満足していないようだ。",
      "一時的なことではない。もう何年も経っている。",
      "他人の人生を見ながら、自分の人生を消費している。",
      "時間を失ったのではない。時間の中で自分を失った。",
      "目が覚めている。それは今ここにいることと同じではない。",
      "必要なものはすべて持っている。それを使う勇気以外は。",
      "許可を待っている。郵便では届かない。",
      "できないのではない。まだそうしたいと決めていないだけだ。",
      "今日も終わる。何をしたと言うつもりか？",
      "休んでいるのではない。逃げているのだ。",
      "かつては人生がすべて前にあった。今は減った。明日はさらに減る。あなたは永遠ではない。",
      "翼は、飛ぶことで自ら作るものだ。",
      "命にそんなにけちで、退屈でさえ気を紛らわせたがる。",
      "自分を愛することさえ怠けている。",
      "今日はまだ遅くない。でも今日は終わりに近づいている。",
      "意味を探しているのではない。言い訳を探しているのだ。",
      "まだここにいる。それは何かだ。でも十分ではない。",
      "今すぐ始めない理由以外、必要なものはすべて持っている。",
      "実現しようともしなかった夢に浸るほうが、それが自分の夢ではなかったと知る危険を冒すより楽だ。",
      "終わった。",
    ],
  'francese': [
      "La matinée est presque terminée. Où étais-tu?",
      "Trois heures ont passé. Et tu ne le savais pas.",
      "La moitié de la journée est déjà partie. Tu ne sais même pas comment.",
      "Tu attends quelque chose. Ça ne viendra pas tout seul.",
      "Chaque heure qui passe n'existe plus.",
      "Tu as encore remis à plus tard. Tu as remis de vivre aussi.",
      "Pendant que tu décides, le temps continue de passer.",
      "Ce soir tu regarderas en arrière. Qu'est-ce que tu verras?",
      "Il n'existe pas de version future de toi qui arrangera tout.",
      "Tu vis ou tu attends seulement de le faire ?",
      "Combien de fois as-tu dit demain?",
      "Ton téléphone sait tout de toi. Même combien de temps tu gaspilles.",
      "Tu vieillis même maintenant, pendant que tu lis cette notification.",
      "L'expérience ne tient pas au nombre de plats différents que tu as mangés, mais à ce que tu as vraiment su savourer.",
      "La vie n'est pas en pause. Seulement toi.",
      "Tu as ouvert cette application. Maintenant, réveille-toi.",
      "Personne ne te rendra cet après-midi.",
      "Tu attends de te sentir prêt. Ça n'arrivera pas, parce que tu l'es déjà.",
      "Aujourd'hui finira. Comme tous les autres jours où tu ne t'es pas écouté.",
      "Tu prends tellement d'élan qu'au moment de partir tu es déjà mort de fatigue. Ou juste mort.",
      "Tu as vérifié ton téléphone 47 fois aujourd'hui. Rien d'important.",
      "Ta liste de choses à faire est plus vieille que tes rêves.",
      "Tu attends la bonne humeur. Ce n'est pas une stratégie.",
      "Chaque notification que tu as ouverte aujourd'hui valait-elle ton temps?",
      "Tu passes plus d'un tiers de l'année à dormir. Tu es plus actif quand tu dors que lorsque tu crois être éveillé.",
      "Ton corps vieillit même quand tu ne fais rien.",
      "Tu as tellement remis à plus tard que tu as oublié ce que tu voulais.",
      "Ce n'est pas de la paresse. C'est de la peur. Et c'est pire.",
      "Dans dix ans tu te souviendras de ce moment comme du temps perdu.",
      "Tu lis ce message au lieu de faire cette chose, précisément celle-là. Tu le sais.",
      "Tu as un rêve dans un tiroir. Le tiroir est fermé depuis des années.",
      "Tu ne te reposes pas. Tu remets juste à plus tard en position horizontale.",
      "Aujourd'hui, tu as dit : « Je le ferai plus tard. » Ce « plus tard » est passé depuis longtemps.",
      "Le temps que tu as gaspillé aujourd'hui ne reviendra pas.",
      "Tu attends que quelqu'un te donne la permission. Elle ne viendra pas.",
      "Tu y as tellement réfléchi qu'au moment de le faire tu as changé d'avis.",
      "La journée se termine. Comme toutes les autres.",
      "Ton potentiel est fatigué de t'attendre.",
      "Chaque jour ressemble au précédent parce que tu continues d'espérer que le destin s'occupe de toi sans toi.",
      "Tu te consumes seul, sans envisager l'autre possibilité : dévorer la vie toi-même.",
      "Chaque jour identique au précédent est un choix.",
      "Comme il est triste, le toi dans 5 ans qui attendait de grandes choses. Mais tu ne t'es pas réveillé.",
      "Réveille-toi et apprends à écouter ceux qui te parlent.",
      "Tu attends la motivation. C'est elle qui t'attend.",
      "As-tu vécu aujourd'hui ou tu es juste passé à travers?",
      "Le problème n'est pas le temps, mais sa profondeur.",
      "Demain commencera exactement comme aujourd'hui. Sauf si tu fais quelque chose maintenant.",
      "Tu collectionnes tant d'idées que tu ne mets jamais en pratique. Tu collectionnes les rêves des autres.",
      "Ta vie n'est pas en construction. Elle est en cours. Maintenant.",
      "Tu as si peur du temps qui passe que tu préfères le tenir loin de toi.",
      "Driiiiiiing. Réveille-toi, tu dors encore.",
      "La vie, c'est exactement maintenant.",
      "Tu as un rêve. Tu as juste oublié où tu l'as mis.",
      "Tu fais défiler l'écran. Ta vie défile et disparaît.",
      "Tu n'as pas remis une chose à plus tard. Tu t'es remis toi-même à plus tard.",
      "Tu es encore là où tu étais hier. Ce n'est pas un hasard.",
      "Tu as besoin d'une pause de quoi, exactement?",
      "Tu réunis toutes les conditions pour être heureux dans le futur. À condition d'y arriver, à cet incroyable futur.",
      "Tu ne te souviendras pas de ce moment. C'est ça le problème.",
      "Tu as tant de vie, mais tu la cherches toujours devant toi.",
      "Le silence que tu entends c'est le temps qui passe.",
      "Ce n'est pas de la fatigue. C'est de la distance avec toi-même.",
      "Tu vis par habitude ou par choix?",
      "As-tu fait quelque chose pour la première fois aujourd'hui?",
      "Il n'est pas trop tard, mais il n'est déjà plus tôt.",
      "Pendant que tu attends le moment parfait qui est toujours dans le futur, le moment parfait s'en fout et prend un verre sans toi.",
      "Tu as peur de commencer ou de finir?",
      "Ce n'est pas que tu ne sais pas quoi faire. C'est que tu sais ce que tu ne fais pas.",
      "Combien de versions de toi as-tu abandonnées en chemin?",
      "Il n'existe pas de bon jour. Il existe seulement celui-ci.",
      "Tu attends de te sentir mieux. Le corps ne ment pas, l'esprit oui.",
      "As-tu bien vérifié les réseaux sociaux, pour t'assurer que rien n'a changé depuis quelques minutes ?",
      "Tu construis quelque chose ou tu regardes juste les autres construire?",
      "Chaque minute qui passe est une minute que tu as choisie.",
      "Ce n'est la faute de personne. C'est plus difficile à accepter comme ça.",
      "Tu vieillis en temps réel. Même maintenant.",
      "À force de remettre à plus tard, tu es devenu la personne qui remet toujours à plus tard.",
      "Tu n'as pas besoin de plus de temps. Tu as besoin de moins de peur.",
      "Tu attends que quelque chose change. Tu es cette chose.",
      "As-tu fait aujourd'hui quelque chose que tu avais peur de faire ?",
      "Ton futur te regarde. Il n'a pas l'air satisfait.",
      "Ce n'est pas une phase. Ça dure depuis des années.",
      "Tu consumes ta vie en regardant celle des autres.",
      "Tu n'as pas perdu le temps. Tu t'es perdu dans le temps.",
      "Tu es éveillé. Ce n'est pas la même chose qu'être présent.",
      "Tu as tout ce dont tu as besoin. Sauf le courage de l'utiliser.",
      "Tu attends la permission. Elle n'arrivera pas par courrier.",
      "Ce n'est pas que tu ne peux pas. C'est que tu n'as pas encore décidé de vouloir.",
      "Aujourd'hui finira. Qu'est-ce que tu diras avoir fait?",
      "Tu ne te reposes pas. Tu évites.",
      "Tu avais toute une vie devant toi. Maintenant, il t'en reste moins. Demain, encore moins. Tu n'es pas éternel.",
      "Tes ailes, tu les construis en volant.",
      "Tu es tellement avare de vie que même l'ennui préfère se distraire.",
      "Trop paresseux pour t'aimer toi-même.",
      "Il n'est pas trop tard pour aujourd'hui. Mais aujourd'hui se termine.",
      "Tu ne cherches pas le sens. Tu cherches une excuse.",
      "Tu es encore là. C'est déjà quelque chose. Mais ce n'est pas suffisant.",
      "Tu as tout ce qu'il te faut sauf une raison de ne pas commencer maintenant.",
      "Mieux vaut se complaire dans les rêves qu'on n'a jamais tenté de réaliser que risquer de découvrir qu'ils n'étaient pas les nôtres.",
      "FINITO.",
    ],
    'espanol': [
      "La mañana casi ha terminado. ¿Dónde has estado?",
      "Han pasado tres horas. Y tú no lo sabías.",
      "La mitad del día ya se fue. Ni siquiera sabes cómo.",
      "Estás esperando algo. No vendrá solo.",
      "Cada hora que pasa ya no existe.",
      "Volviste a posponer. Pospusiste vivir también.",
      "Mientras decides, el tiempo sigue pasando.",
      "Esta noche mirarás atrás. ¿Qué verás?",
      "No existe una versión futura de ti que lo arreglará todo.",
      "¿Estás viviendo o solo esperando hacerlo?",
      "¿Cuántas veces has dicho mañana?",
      "Tu teléfono lo sabe todo de ti. También cuánto tiempo desperdicias.",
      "Estás envejeciendo incluso ahora, mientras lees esta notificación.",
      "La experiencia no consiste en cuántas comidas distintas has probado, sino en cuánto has saboreado algo de verdad.",
      "La vida no está en pausa. Solo tú.",
      "Abriste esta aplicación. Ahora despierta.",
      "Nadie te devolverá esta tarde.",
      "Estás esperando sentirte listo. No sucederá, porque ya lo estás.",
      "Hoy terminará. Como todos los demás días en los que no te escuchaste.",
      "Tomas tanto impulso que cuando tienes que partir ya estás muerto de cansancio. O solo muerto.",
      "Revisaste el teléfono 47 veces hoy. Nada importante.",
      "Tu lista de cosas por hacer es más vieja que tus sueños.",
      "Estás esperando el estado de ánimo correcto. Eso no es una estrategia.",
      "¿Cada notificación que abriste hoy valía tu tiempo?",
      "Pasas más de un tercio del año durmiendo. Eres más activo cuando duermes que cuando crees estar despierto.",
      "Tu cuerpo envejece incluso cuando no haces nada.",
      "Has postergado tanto que olvidaste lo que querías.",
      "No es pereza. Es miedo. Y eso es peor.",
      "En diez años recordarás este momento como tiempo perdido.",
      "Estás leyendo este mensaje en vez de hacer esa cosa, precisamente esa cosa. Lo sabes.",
      "Tienes un sueño en un cajón. El cajón lleva años cerrado.",
      "No estás descansando. Solo estás postergando en posición horizontal.",
      "Hoy dijiste: «Lo haré después». Ese «después» pasó hace mucho.",
      "El tiempo que desperdiciaste hoy no volverá.",
      "Estás esperando que alguien te dé permiso. No llegará.",
      "Pensaste tanto en qué hacer que ahora que vas a hacerlo cambiaste de opinión.",
      "El día está terminando. Como todos los demás.",
      "Tu potencial está cansado de esperarte.",
      "Cada día es igual al anterior porque sigues esperando que el destino se ocupe de ti sin ti.",
      "Te consumes a solas, sin considerar la alternativa: consumir tú la vida.",
      "Cada día igual al anterior es una elección.",
      "Qué triste la versión de ti en 5 años que esperaba grandes cosas. Pero nunca despertaste.",
      "Despierta y aprende a escuchar a quienes te hablan.",
      "Estás esperando la motivación. Ella te está esperando a ti.",
      "¿Viviste hoy o solo lo atravesaste?",
      "El problema no es el tiempo, sino su profundidad.",
      "Mañana empezará exactamente igual que hoy. A menos que hagas algo ahora.",
      "Estás coleccionando muchísimas ideas que nunca llevas a la práctica. Coleccionas los sueños de los demás.",
      "Tu vida no está en construcción. Está en curso. Ahora.",
      "Tienes tanto miedo al paso del tiempo que prefieres mantenerlo lejos de ti.",
      "Riiiiiiiing. Despierta, que todavía estás durmiendo.",
      "La vida es exactamente ahora.",
      "Tienes un sueño. Solo olvidaste dónde lo pusiste.",
      "Estás haciendo scroll. Tu vida se va con cada deslizamiento.",
      "No postergaste una cosa. Te postergaste a ti mismo.",
      "Sigues donde estabas ayer. No es casualidad.",
      "¿Necesitas un descanso de qué, exactamente?",
      "Estás creando todas las condiciones para ser feliz en el futuro. Siempre que llegues a ese increíble futuro.",
      "No recordarás este momento. Ese es el problema.",
      "Tienes tanta vida, pero sigues buscándola delante de ti.",
      "El silencio que escuchas es el tiempo que pasa.",
      "No es cansancio. Es distancia de ti mismo.",
      "¿Vives por hábito o por elección?",
      "¿Hiciste algo por primera vez hoy?",
      "No es demasiado tarde, pero tampoco es temprano.",
      "Mientras esperas el momento perfecto que siempre está en el futuro, el momento perfecto pasa de ti y se toma una copa sin ti.",
      "¿Tienes miedo de empezar o de terminar?",
      "No es que no sepas qué hacer. Es que sabes lo que no estás haciendo.",
      "¿Cuántas versiones de ti has abandonado por el camino?",
      "No existe el día correcto. Solo existe este.",
      "Estás esperando sentirte mejor. El cuerpo no miente, la mente sí.",
      "¿Revisaste bien las redes sociales, para asegurarte de que nada haya cambiado desde hace unos minutos?",
      "¿Estás construyendo algo o solo mirando a otros construir?",
      "Cada minuto que pasa es un minuto que elegiste.",
      "No es culpa de nadie. Es más difícil aceptarlo así.",
      "Estás envejeciendo en tiempo real. También ahora.",
      "De tanto posponer, te has convertido en la persona que siempre pospone.",
      "No necesitas más tiempo. Necesitas menos miedo.",
      "Estás esperando que algo cambie. Tú eres esa cosa.",
      "¿Hoy hiciste algo que tenías miedo de hacer?",
      "Tu futuro te está mirando. No parece satisfecho.",
      "No es una fase. Son años.",
      "Estás consumiendo tu vida mirando la de los demás.",
      "No perdiste el tiempo. Te perdiste a ti mismo en el tiempo.",
      "Estás despierto. No es lo mismo que estar presente.",
      "Tienes todo lo que necesitas. Excepto el coraje de usarlo.",
      "Estás esperando el permiso. No llegará por correo.",
      "No es que no puedas. Es que todavía no has decidido querer.",
      "Hoy terminará. ¿Qué dirás que hiciste?",
      "No estás descansando. Estás evitando.",
      "Tenías toda una vida por delante. Ahora tienes menos. Mañana, aún menos. No eres eterno.",
      "Las alas te las haces volando.",
      "Eres tan avaro con la vida que hasta el aburrimiento prefiere distraerse.",
      "Demasiado perezoso para amarte a ti mismo.",
      "No es demasiado tarde para hoy. Pero hoy está terminando.",
      "No estás buscando el sentido. Estás buscando una excusa.",
      "Sigues aquí. Ya es algo. Pero no es suficiente.",
      "Tienes todo lo que necesitas menos una razón para no empezar ahora.",
      "Mejor recrearse en los sueños que nunca intentaste realizar que arriesgarse a descubrir que no eran los tuyos.",
      "FINITO.",
    ],
  };

  static String casuale(String lingua) {
    final lista = tutte[lingua] ?? tutte['english']!;
    return lista[Random().nextInt(lista.length)];
  }
}
