import 'dart:math';

class Frasi {
  static Map<String, List<String>> tutte = {
    'italiano': [
      "La mattina è quasi finita. Tu dove sei stato?",
      "Sono passate tre ore. E tu non lo sai.",
      "Metà giornata è già andata. Non sai nemmeno come.",
      "Stai aspettando qualcosa. Non arriverà da solo.",
      "Ogni ora che passa non esiste più.",
      "Hai rimandato ancora. Hai rimandato anche di vivere.",
      "Mentre decidi, il tempo continua a passare.",
      "Questa sera guarderai indietro. Cosa vedrai?",
      "Non c'è una versione futura di te che sistemerà tutto.",
      "Stai vivendo o stai solo aspettando di vivere?",
      "Quante volte hai detto domani?",
      "Il tuo telefono sa tutto di te. Anche quanto tempo sprechi.",
      "Stai invecchiando anche adesso, mentre leggi questo.",
      "Non ricordi cosa hai fatto ieri. Figuriamoci tra un anno.",
      "La vita non è in pausa. Solo tu lo sei.",
      "Hai aperto questa app. Significa che sai.",
      "Nessuno ti restituirà questo pomeriggio.",
      "Stai aspettando di sentirti pronto. Non succederà.",
      "Oggi finirà. Come tutti gli altri giorni che hai sprecato.",
      "Prendi così tanta rincorsa che quando devi partire sei stanco morto. O solo morto.",
      "Hai controllato il telefono 47 volte oggi. Niente di importante.",
      "La tua lista di cose da fare è più vecchia dei tuoi sogni.",
      "Stai aspettando l'umore giusto. Non è una strategia.",
      "Ogni notifica che hai aperto oggi valeva il tuo tempo?",
      "Passi un anno, più di un terzo dormendo. Sei più attivo di quando ti svegli.",
      "Il tuo corpo invecchia anche quando non fai nulla.",
      "Hai rimandato così tanto che hai dimenticato cosa volevi.",
      "Non è pigrizia. È paura. Ed è peggio.",
      "Tra dieci anni ricorderai questo momento come tempo perso.",
      "Stai leggendo questo invece di fare quella cosa. Lo sai.",
      "Hai un sogno nel cassetto. Il cassetto è chiuso da anni.",
      "Non stai riposando. Stai solo rimandando in posizione orizzontale.",
      "Oggi hai detto dopo. Dopo è già passato.",
      "Il tempo che hai sprecato oggi non tornerà nemmeno se lo chiedi gentilmente.",
      "Stai aspettando che qualcuno ti dia il permesso. Non arriverà.",
      "Hai così tanto pensato a cosa fare che adesso che stai per farlo hai cambiato idea.",
      "La giornata sta finendo. Come tutte le altre.",
      "Il tuo potenziale è stanco di aspettarti.",
      "Ogni giorno è uguale a quello precedente.",
      "Ti consumi da solo.",
      "Ogni giorno uguale al precedente è una scelta.",
      "Che triste la versione di te tra 5 anni che si aspettava grandi cose. Ma tu non ti sei svegliato.",
      "Svegliati e impara ad ascoltare chi ti parla invece di pensare che dovresti.",
      "Stai aspettando la motivazione. È lei che aspetta te.",
      "Hai vissuto oggi o l'hai solo attraversato?",
      "Il problema non è il tempo. Sei tu.",
      "Domani inizierà esattamente come oggi. A meno che tu non faccia qualcosa adesso.",
      "Stai collezionando giorni vuoti.",
      "La tua vita non è in costruzione. È in corso. Adesso.",
      "Hai così paura della spontaneità che critichi tutti. Che spreco.",
      "Driiiiiiinnnnnn. Sveglia, che stai ancora dormendo.",
      "Tutto vuole vivere e tu non lasci che la vitalità si apra al mondo come un fiore.",
      "Hai un sogno. Hai solo dimenticato dove l'hai messo.",
      "Stai scrollando. La tua vita scorre insieme.",
      "Non hai rimandato una cosa. Hai rimandato te stesso.",
      "Sei ancora lì dove eri ieri. Non è un caso.",
      "Hai bisogno di una pausa da cosa, esattamente?",
      "Stai aspettando di essere felice per iniziare. È il contrario.",
      "Non ricorderai questo momento. È questo il problema.",
      "Hai tutta la vita davanti. Stai usando bene questa parte?",
      "Il silenzio che senti è il tempo che passa.",
      "Non è stanchezza. È distanza da te stesso.",
      "Stai vivendo per abitudine o per scelta?",
      "Oggi hai fatto qualcosa per la prima volta?",
      "Non è troppo tardi. Ma non è presto neanche.",
      "Mentre aspetti il momento perfetto che è sempre futuro, il momento perfetto se ne sbatte e si prende un aperitivo senza te.",
      "Hai paura di iniziare o di finire?",
      "Non è che non sai cosa fare. È che sai cosa non stai facendo.",
      "Quante versioni di te hai abbandonato per strada?",
      "Non esiste il giorno giusto. Esiste solo questo.",
      "Stai aspettando di sentirti meglio. Il corpo non mente, la mente sì.",
      "Hai controllato i social. Niente di tuo è cambiato.",
      "Stai costruendo qualcosa o stai solo guardando gli altri costruire?",
      "Ogni minuto che passa è un minuto che hai scelto.",
      "Non è colpa di nessuno. È più difficile da accettare così.",
      "Stai invecchiando in tempo reale. Anche adesso.",
      "Hai rimandato così tante volte che rimandare è diventato chi sei.",
      "Non ti serve più tempo. Ti serve meno paura.",
      "Stai aspettando che qualcosa cambi. Sei tu quella cosa.",
      "Oggi hai fatto qualcosa che ti spaventa?",
      "Il tuo futuro ti sta guardando. Non sembra soddisfatto.",
      "Non è una fase. Sono anni.",
      "Stai consumando la tua vita guardando quella degli altri.",
      "Non hai perso il tempo. Hai perso te stesso nel tempo.",
      "Sei sveglio. Non è la stessa cosa di essere presente.",
      "Hai tutto quello che ti serve. Tranne il coraggio di usarlo.",
      "Stai aspettando il permesso. Non arriverà per posta.",
      "Non è che non puoi. È che non hai ancora deciso di volere.",
      "Oggi finirà. Cosa dirai che hai fatto?",
      "Non stai riposando. Stai evitando.",
      "Avevi una vita davanti. Ora ne hai meno. Domani ancora meno. Muoviti e svegliati.",
      "Le ali crescono volando.",
      "Sei così avaro di vita che pure la noia preferisce distrarsi.",
      "Pronto? Lazzaro, alzati e cammina.",
      "Non è troppo tardi per oggi. Ma oggi sta finendo.",
      "Non stai cercando il senso. Stai cercando una scusa.",
      "Sei ancora qui. È già qualcosa. Ma non basta.",
      "Hai tutto quello che ti serve tranne una ragione per non iniziare adesso.",
      "FINITO.",
    ],
    'english': [
      "The morning is almost over. Where have you been?",
      "Three hours have passed. And you didn't notice.",
      "Half the day is already gone. You don't even know how.",
      "You're waiting for something. It won't come on its own.",
      "Every hour that passes no longer exists.",
      "You postponed again. You postponed living too.",
      "While you decide, time keeps moving.",
      "Tonight you'll look back. What will you see?",
      "There is no future version of you that will fix everything.",
      "Are you living or just waiting to live?",
      "How many times have you said tomorrow?",
      "Your phone knows everything about you. Including how much time you waste.",
      "You're aging right now, as you read this.",
      "You don't remember what you did yesterday. Imagine in a year.",
      "Life is not on pause. Only you are.",
      "You opened this app. That means you know.",
      "No one will give you this afternoon back.",
      "You're waiting to feel ready. It won't happen.",
      "Today will end. Like all the other days you wasted.",
      "You take such a long run-up that by the time you're ready to go, you're already dead tired. Or just dead.",
      "You checked your phone 47 times today. Nothing important.",
      "Your to-do list is older than your dreams.",
      "You're waiting for the right mood. That's not a strategy.",
      "Was every notification you opened today worth your time?",
      "You spend a year, more than a third of it sleeping. You're more active when you wake up.",
      "Your body ages even when you do nothing.",
      "You've postponed so much you forgot what you wanted.",
      "It's not laziness. It's fear. And that's worse.",
      "In ten years you'll remember this moment as wasted time.",
      "You're reading this instead of doing that thing. You know it.",
      "You have a dream in a drawer. The drawer has been closed for years.",
      "You're not resting. You're just postponing horizontally.",
      "You said later today. Later is already gone.",
      "The time you wasted today won't come back even if you ask nicely.",
      "You're waiting for someone to give you permission. It won't come.",
      "You thought about it so long that now you're about to do it, you've changed your mind.",
      "The day is ending. Like all the others.",
      "Your potential is tired of waiting for you.",
      "Every day is the same as the one before.",
      "You consume yourself.",
      "Every day the same as the previous one is a choice.",
      "How sad the version of you in 5 years that expected great things. But you never woke up.",
      "Wake up and learn to listen to those who speak to you instead of thinking you should.",
      "You're waiting for motivation. It's waiting for you.",
      "Did you live today or just pass through it?",
      "The problem is not time. It's you.",
      "Tomorrow will start exactly like today. Unless you do something now.",
      "You're collecting empty days.",
      "Your life is not under construction. It's happening. Right now.",
      "You're so afraid of spontaneity that you criticize everyone. What a waste.",
      "Riiiiiiing. Wake up, you're still sleeping.",
      "Everything wants to live and you won't let your vitality open to the world like a flower.",
      "You have a dream. You just forgot where you put it.",
      "You're scrolling. Your life scrolls with it.",
      "You didn't postpone a thing. You postponed yourself.",
      "You're still where you were yesterday. That's not a coincidence.",
      "You need a break from what, exactly?",
      "You're waiting to be happy before you start. It's the other way around.",
      "You won't remember this moment. That's the problem.",
      "You have your whole life ahead. Are you using this part well?",
      "The silence you hear is time passing.",
      "It's not tiredness. It's distance from yourself.",
      "Are you living by habit or by choice?",
      "Did you do something for the first time today?",
      "It's not too late. But it's not early either.",
      "While you wait for the perfect moment that is always in the future, the perfect moment doesn't care and goes for a drink without you.",
      "Are you afraid to start or to finish?",
      "It's not that you don't know what to do. It's that you know what you're not doing.",
      "How many versions of yourself have you left behind?",
      "There is no right day. There is only this one.",
      "You're waiting to feel better. The body doesn't lie, the mind does.",
      "You checked social media. Nothing of yours has changed.",
      "Are you building something or just watching others build?",
      "Every minute that passes is a minute you chose.",
      "It's nobody's fault. That's harder to accept.",
      "You're aging in real time. Even now.",
      "You've postponed so many times that postponing has become who you are.",
      "You don't need more time. You need less fear.",
      "You're waiting for something to change. You are that something.",
      "Did you do something that scared you today?",
      "Your future is watching you. It doesn't look satisfied.",
      "It's not a phase. It's been years.",
      "You're consuming your life watching everyone else's.",
      "You didn't lose time. You lost yourself in time.",
      "You're awake. That's not the same as being present.",
      "You have everything you need. Except the courage to use it.",
      "You're waiting for permission. It won't arrive by post.",
      "It's not that you can't. It's that you haven't decided you want to yet.",
      "Today will end. What will you say you did?",
      "You're not resting. You're avoiding.",
      "You had a whole life ahead. Now you have less. Tomorrow even less. Move and wake up.",
      "Wings grow by flying.",
      "You're so stingy with life that even boredom prefers to distract itself.",
      "Ready? Lazarus, rise and walk.",
      "It's not too late for today. But today is ending.",
      "You're not looking for meaning. You're looking for an excuse.",
      "You're still here. That's something. But it's not enough.",
      "You have everything you need except a reason not to start right now.",
      "FINITO.",
    ],
    'zhongwen': [
      "早晨快结束了。你在哪里？",
      "三个小时过去了。你不知道。",
      "半天已经消失了。你不知道怎么发生的。",
      "你在等待什么。它不会自己来。",
      "每一个过去的小时都不再存在。",
      "你又推迟了。你也推迟了活着。",
      "当你犹豫时，时间继续流逝。",
      "今晚你会回头看。你会看到什么？",
      "没有未来的你会修复一切。",
      "你是在生活，还是只是在等待生活？",
      "你说了多少次明天？",
      "你的手机了解你的一切。包括你浪费了多少时间。",
      "你正在变老。就在此刻。",
      "你不记得昨天做了什么。更别说一年后了。",
      "生活没有暂停。只有你暂停了。",
      "你打开了这个应用。说明你知道。",
      "没有人会把这个下午还给你。",
      "你在等待感觉准备好。不会发生的。",
      "今天会结束。就像你浪费的所有其他日子一样。",
      "你助跑那么长，到要出发时已经累死了。或者只是死了。",
      "你今天检查了47次手机。没有任何重要的事。",
      "你的待办清单比你的梦想更古老。",
      "你在等待合适的心情。这不是策略。",
      "你今天打开的每条通知都值得你的时间吗？",
      "你花了一年多，三分之一在睡觉。醒来时你更有活力。",
      "你的身体即使在你什么都不做的时候也在老去。",
      "你推迟了太多，以至于忘记了自己想要什么。",
      "不是懒惰。是恐惧。这更糟糕。",
      "十年后你会记得这一刻是浪费的时间。",
      "你在读这个而不是做那件事。你知道的。",
      "你有一个梦想放在抽屉里。抽屉已经关了好几年了。",
      "你不是在休息。你只是在水平位置上推迟。",
      "你今天说了以后。以后已经过去了。",
      "你今天浪费的时间不会回来。",
      "你在等待某人给你许可。不会来的。",
      "你想了那么久该做什么，现在要做了，你又改变主意了。",
      "这一天要结束了。就像所有其他的一样。",
      "你的潜力已经厌倦了等你。",
      "每天都和前一天一样。",
      "你在消耗自己。",
      "每天和前一天一样是一种选择。",
      "多么悲哀，五年后的你期待着伟大的事情。但你从未醒来。",
      "醒来，学会倾听和你说话的人。",
      "你在等待动力。它在等你。",
      "你今天是活着还是只是经过？",
      "问题不是时间。是你。",
      "明天会和今天一样开始。除非你现在做些什么。",
      "你在收集空洞的日子。",
      "你的生活不是在建设中。它正在发生。就在现在。",
      "你如此害怕自发性，以至于批评所有人。真是浪费。",
      "叮铃铃！醒醒，你还在睡觉。",
      "一切都想活着，而你不让你的活力像花一样向世界绽放。",
      "你有一个梦想。你只是忘了放在哪里。",
      "你在刷屏。你的生活也在一起滚动。",
      "你没有推迟一件事。你推迟了你自己。",
      "你还在昨天的地方。这不是巧合。",
      "你需要从什么中休息？",
      "你在等待快乐才开始。顺序是反的。",
      "你不会记得这一刻。这就是问题所在。",
      "你有整个人生在前面。你在好好利用这一部分吗？",
      "你听到的沉默是时间流逝的声音。",
      "不是疲惫。是与自己的距离。",
      "你是出于习惯还是出于选择而活着？",
      "今天你做了第一次的事情吗？",
      "还不太晚。但也不早了。",
      "当你等待完美时刻时，完美时刻不在乎，自己去喝酒了，没有你。",
      "你害怕开始还是结束？",
      "不是你不知道该做什么。是你知道你没在做什么。",
      "你在路上抛弃了多少个版本的自己？",
      "没有正确的日子。只有这一天。",
      "你在等感觉好一点。身体不说谎，心智会。",
      "你查看了社交媒体。你的什么都没有改变。",
      "你在建造什么，还是只是看别人建造？",
      "每一分钟的流逝都是你选择的。",
      "不是任何人的错。这样更难接受。",
      "你在实时老去。就在现在。",
      "你推迟了那么多次，推迟已经成为你是谁。",
      "你不需要更多时间。你需要更少的恐惧。",
      "你在等待某些事情改变。你就是那件事。",
      "今天你做了让你害怕的事情吗？",
      "你的未来在看着你。它看起来不满意。",
      "不是一个阶段。已经是好几年了。",
      "你在看别人的生活中消耗自己的生活。",
      "你没有失去时间。你在时间中失去了自己。",
      "你醒着。这和存在于当下不是一回事。",
      "你拥有你需要的一切。除了使用它的勇气。",
      "你在等待许可。它不会邮寄来的。",
      "不是你不能。是你还没决定你想要。",
      "今天会结束。你会说你做了什么？",
      "你不是在休息。你在逃避。",
      "你曾经有整个人生在前面。现在少了。明天更少。动起来，醒来。",
      "翅膀在飞翔中生长。",
      "你如此吝啬生命，连无聊都宁愿分心。",
      "准备好了吗？拉撒路，起来走吧。",
      "今天还没太晚。但今天要结束了。",
      "你不是在寻找意义。你在寻找借口。",
      "你还在这里。这已经是什么了。但还不够。",
      "你拥有一切你需要的，除了现在就开始的理由。",
      "结束了。",
    ],
    'nihongo': [
      "朝がもう終わりそうだ。あなたはどこにいたの？",
      "三時間が過ぎた。あなたは気づかなかった。",
      "半日がもう消えた。どうやってそうなったかわからない。",
      "何かを待っている。それは自分では来ない。",
      "過ぎ去った時間はもう存在しない。",
      "またも先延ばしにした。生きることも先延ばしにした。",
      "迷っている間も、時間は流れ続ける。",
      "今夜、振り返るだろう。何が見える？",
      "すべてを修正してくれる未来の自分など存在しない。",
      "生きているのか、それともただ生きるのを待っているのか？",
      "「明日」と何回言った？",
      "あなたのスマホはあなたのすべてを知っている。どれだけ時間を無駄にしているかも。",
      "今この瞬間も、あなたは老いている。",
      "昨日何をしたか覚えていない。一年後はもっとそうだろう。",
      "人生は一時停止していない。あなただけが止まっている。",
      "このアプリを開いた。つまりわかっているということだ。",
      "この午後をあなたに返してくれる人はいない。",
      "準備ができたと感じるのを待っている。それは来ない。",
      "今日も終わる。無駄にした他の日々と同じように。",
      "助走をとりすぎて、いざ出発しようとしたら疲れ果てていた。あるいはただ死んでいた。",
      "今日スマホを47回チェックした。大事なことは何もなかった。",
      "あなたのやることリストは夢より古い。",
      "正しい気分を待っている。それは戦略ではない。",
      "今日開いた通知は、あなたの時間に値するものだったか？",
      "一年の三分の一以上を眠って過ごす。起きているときの方がまだましだ。",
      "何もしていなくても、体は老いていく。",
      "先延ばしにしすぎて、何が欲しかったか忘れてしまった。",
      "怠惰じゃない。恐怖だ。それの方がもっと悪い。",
      "十年後、この瞬間を無駄な時間として思い出すだろう。",
      "あのことをする代わりにこれを読んでいる。わかっているだろう。",
      "夢は引き出しの中にある。引き出しは何年も閉まったままだ。",
      "休んでいるのではない。ただ横になって先延ばしにしているだけだ。",
      "今日「後で」と言った。後でもう過ぎた。",
      "今日無駄にした時間は戻ってこない。",
      "誰かが許可を与えてくれるのを待っている。来ない。",
      "何をするか考えすぎて、いざやろうとしたら気が変わった。",
      "この日も終わる。他のすべての日と同じように。",
      "あなたの可能性は、あなたを待つのに疲れた。",
      "毎日が前の日と同じだ。",
      "自分自身を消耗している。",
      "毎日前の日と同じというのは、選択だ。",
      "五年後のあなたが大きなことを期待していたなんて、なんと悲しい。でもあなたは目覚めなかった。",
      "目覚めて、話しかけてくれる人の声を聞くことを学べ。",
      "やる気を待っている。やる気があなたを待っている。",
      "今日は生きたか、それともただ通り過ぎただけか？",
      "問題は時間ではない。あなただ。",
      "明日も今日と同じように始まる。今何かしない限り。",
      "空っぽの日々を集めている。",
      "あなたの人生は建設中ではない。今まさに起きている。",
      "自発性をそんなに恐れて、みんなを批判している。なんともったいない。",
      "リリリリン！起きて、まだ寝ている。",
      "すべてのものが生きたがっている。なのにあなたは自分の活力が花のように世界に開くのを許さない。",
      "夢がある。どこに置いたか忘れただけだ。",
      "スクロールしている。あなたの人生も一緒に流れていく。",
      "何かを先延ばしにしたのではない。自分自身を先延ばしにした。",
      "昨日と同じ場所にいる。偶然ではない。",
      "一体何から休憩が必要なのか？",
      "幸せになってから始めようと待っている。順序が逆だ。",
      "この瞬間を覚えていないだろう。それが問題だ。",
      "人生はまだ前にある。この部分をうまく使っているか？",
      "聞こえる沈黙は、時間が過ぎていく音だ。",
      "疲れではない。自分自身からの距離だ。",
      "習慣で生きているのか、選択で生きているのか？",
      "今日、初めてのことをしたか？",
      "遅すぎではない。でも早くもない。",
      "完璧な瞬間を待っている間に、完璧な瞬間はどうでもよくなって、あなたなしで一杯飲みに行った。",
      "始めることが怖いのか、終わることが怖いのか？",
      "何をすべきかわからないのではない。何をしていないかわかっているのだ。",
      "道中、何人の自分を置き去りにしてきた？",
      "正しい日などない。あるのはこの日だけだ。",
      "良くなるのを待っている。体は嘘をつかない、心はつく。",
      "SNSをチェックした。あなたの何も変わっていない。",
      "何かを作っているのか、それともただ他人が作るのを見ているのか？",
      "過ぎ去る一分一分は、あなたが選んだ一分だ。",
      "誰のせいでもない。そう認めるのがもっと難しい。",
      "今この瞬間も、リアルタイムで老いていく。",
      "何度も先延ばしにしすぎて、先延ばしがあなた自身になってしまった。",
      "もっと時間が必要なのではない。もっと少ない恐惧が必要だ。",
      "何かが変わるのを待っている。あなたがその何かだ。",
      "今日、怖いことをしたか？",
      "未来のあなたがあなたを見ている。満足していないようだ。",
      "一時的なことではない。もう何年も経っている。",
      "他人の人生を見ながら、自分の人生を消費している。",
      "時間を失ったのではない。時間の中で自分を失った。",
      "目が覚めている。それは今ここにいることと同じではない。",
      "必要なものはすべて持っている。それを使う勇気以外は。",
      "許可を待っている。郵便では届かない。",
      "できないのではない。まだそうしたいと決めていないだけだ。",
      "今日も終わる。何をしたと言うつもりか？",
      "休んでいるのではない。逃げているのだ。",
      "かつては人生がすべて前にあった。今はもう少ない。明日はさらに少ない。動いて、目覚めろ。",
      "翼は飛ぶことで育つ。",
      "命にそんなにけちで、退屈でさえ気を紛らわせたがる。",
      "準備できた？ラザロよ、立ち上がって歩け。",
      "今日はまだ遅くない。でも今日は終わりに近づいている。",
      "意味を探しているのではない。言い訳を探しているのだ。",
      "まだここにいる。それは何かだ。でも十分ではない。",
      "今すぐ始めない理由以外、必要なものはすべて持っている。",
      "終わった。",
    ],
  'francese': [
      "La matinée est presque terminée. Où étais-tu?",
      "Trois heures ont passé. Et tu ne le savais pas.",
      "La moitié de la journée est déjà partie. Tu ne sais même pas comment.",
      "Tu attends quelque chose. Ça ne viendra pas tout seul.",
      "Chaque heure qui passe n'existe plus.",
      "Tu as encore remis à plus tard. Tu as remis de vivre aussi.",
      "Pendant que tu décides, le temps continue de passer.",
      "Ce soir tu regarderas en arrière. Qu'est-ce que tu verras?",
      "Il n'existe pas de version future de toi qui arrangera tout.",
      "Tu vis ou tu attends juste de vivre?",
      "Combien de fois as-tu dit demain?",
      "Ton téléphone sait tout de toi. Même combien de temps tu gaspilles.",
      "Tu vieillis en ce moment même, pendant que tu lis ceci.",
      "Tu ne te souviens pas de ce que tu as fait hier. Imagine dans un an.",
      "La vie n'est pas en pause. Seulement toi.",
      "Tu as ouvert cette app. Ça veut dire que tu sais.",
      "Personne ne te rendra cet après-midi.",
      "Tu attends de te sentir prêt. Ça n'arrivera pas.",
      "Aujourd'hui finira. Comme tous les autres jours que tu as gaspillés.",
      "Tu prends tellement d'élan qu'au moment de partir tu es déjà mort de fatigue. Ou juste mort.",
      "Tu as vérifié ton téléphone 47 fois aujourd'hui. Rien d'important.",
      "Ta liste de choses à faire est plus vieille que tes rêves.",
      "Tu attends la bonne humeur. Ce n'est pas une stratégie.",
      "Chaque notification que tu as ouverte aujourd'hui valait-elle ton temps?",
      "Tu passes un an, plus d'un tiers à dormir. Tu es plus actif quand tu te réveilles.",
      "Ton corps vieillit même quand tu ne fais rien.",
      "Tu as tellement remis à plus tard que tu as oublié ce que tu voulais.",
      "Ce n'est pas de la paresse. C'est de la peur. Et c'est pire.",
      "Dans dix ans tu te souviendras de ce moment comme du temps perdu.",
      "Tu lis ceci au lieu de faire cette chose. Tu le sais.",
      "Tu as un rêve dans un tiroir. Le tiroir est fermé depuis des années.",
      "Tu ne te reposes pas. Tu remets juste à plus tard en position horizontale.",
      "Tu as dit plus tard aujourd'hui. Plus tard est déjà passé.",
      "Le temps que tu as gaspillé aujourd'hui ne reviendra pas.",
      "Tu attends que quelqu'un te donne la permission. Elle ne viendra pas.",
      "Tu y as tellement réfléchi qu'au moment de le faire tu as changé d'avis.",
      "La journée se termine. Comme toutes les autres.",
      "Ton potentiel est fatigué de t'attendre.",
      "Chaque jour est identique au précédent.",
      "Tu te consumes toi-même.",
      "Chaque jour identique au précédent est un choix.",
      "Comme il est triste, le toi dans 5 ans qui attendait de grandes choses. Mais tu ne t'es pas réveillé.",
      "Réveille-toi et apprends à écouter ceux qui te parlent.",
      "Tu attends la motivation. C'est elle qui t'attend.",
      "As-tu vécu aujourd'hui ou tu es juste passé à travers?",
      "Le problème ce n'est pas le temps. C'est toi.",
      "Demain commencera exactement comme aujourd'hui. Sauf si tu fais quelque chose maintenant.",
      "Tu collectionnes des journées vides.",
      "Ta vie n'est pas en construction. Elle est en cours. Maintenant.",
      "Tu as tellement peur de la spontanéité que tu critiques tout le monde. Quel gâchis.",
      "Driiiiiiing. Réveille-toi, tu dors encore.",
      "Tout veut vivre et tu ne laisses pas ta vitalité s'ouvrir au monde comme une fleur.",
      "Tu as un rêve. Tu as juste oublié où tu l'as mis.",
      "Tu scrolles. Ta vie défile avec.",
      "Tu n'as pas remis une chose à plus tard. Tu t'es remis toi-même à plus tard.",
      "Tu es encore là où tu étais hier. Ce n'est pas un hasard.",
      "Tu as besoin d'une pause de quoi, exactement?",
      "Tu attends d'être heureux pour commencer. C'est l'inverse.",
      "Tu ne te souviendras pas de ce moment. C'est ça le problème.",
      "Tu as toute la vie devant toi. Tu utilises bien cette partie?",
      "Le silence que tu entends c'est le temps qui passe.",
      "Ce n'est pas de la fatigue. C'est de la distance avec toi-même.",
      "Tu vis par habitude ou par choix?",
      "As-tu fait quelque chose pour la première fois aujourd'hui?",
      "Il n'est pas trop tard. Mais il n'est pas tôt non plus.",
      "Pendant que tu attends le moment parfait qui est toujours dans le futur, le moment parfait s'en fout et prend un verre sans toi.",
      "Tu as peur de commencer ou de finir?",
      "Ce n'est pas que tu ne sais pas quoi faire. C'est que tu sais ce que tu ne fais pas.",
      "Combien de versions de toi as-tu abandonnées en chemin?",
      "Il n'existe pas de bon jour. Il existe seulement celui-ci.",
      "Tu attends de te sentir mieux. Le corps ne ment pas, l'esprit oui.",
      "Tu as vérifié les réseaux sociaux. Rien de toi n'a changé.",
      "Tu construis quelque chose ou tu regardes juste les autres construire?",
      "Chaque minute qui passe est une minute que tu as choisie.",
      "Ce n'est la faute de personne. C'est plus difficile à accepter comme ça.",
      "Tu vieillis en temps réel. Même maintenant.",
      "Tu as tellement remis à plus tard que remettre à plus tard est devenu qui tu es.",
      "Tu n'as pas besoin de plus de temps. Tu as besoin de moins de peur.",
      "Tu attends que quelque chose change. Tu es cette chose.",
      "As-tu fait quelque chose qui te fait peur aujourd'hui?",
      "Ton futur te regarde. Il n'a pas l'air satisfait.",
      "Ce n'est pas une phase. Ça dure depuis des années.",
      "Tu consumes ta vie en regardant celle des autres.",
      "Tu n'as pas perdu le temps. Tu t'es perdu dans le temps.",
      "Tu es éveillé. Ce n'est pas la même chose qu'être présent.",
      "Tu as tout ce dont tu as besoin. Sauf le courage de l'utiliser.",
      "Tu attends la permission. Elle n'arrivera pas par courrier.",
      "Ce n'est pas que tu ne peux pas. C'est que tu n'as pas encore décidé de vouloir.",
      "Aujourd'hui finira. Qu'est-ce que tu diras avoir fait?",
      "Tu ne te reposes pas. Tu évites.",
      "Tu avais toute une vie devant toi. Maintenant tu en as moins. Demain encore moins. Bouge et réveille-toi.",
      "Les ailes poussent en volant.",
      "Tu es tellement avare de vie que même l'ennui préfère se distraire.",
      "Prêt? Lazare, lève-toi et marche.",
      "Il n'est pas trop tard pour aujourd'hui. Mais aujourd'hui se termine.",
      "Tu ne cherches pas le sens. Tu cherches une excuse.",
      "Tu es encore là. C'est déjà quelque chose. Mais ce n'est pas suffisant.",
      "Tu as tout ce qu'il te faut sauf une raison de ne pas commencer maintenant.",
      "FINITO.",
    ],
    'espanol': [
      "La mañana casi ha terminado. ¿Dónde has estado?",
      "Han pasado tres horas. Y tú no lo sabías.",
      "La mitad del día ya se fue. Ni siquiera sabes cómo.",
      "Estás esperando algo. No vendrá solo.",
      "Cada hora que pasa ya no existe.",
      "Volviste a posponer. Pospusiste vivir también.",
      "Mientras decides, el tiempo sigue pasando.",
      "Esta noche mirarás atrás. ¿Qué verás?",
      "No existe una versión futura de ti que lo arreglará todo.",
      "¿Estás viviendo o solo esperando vivir?",
      "¿Cuántas veces has dicho mañana?",
      "Tu teléfono lo sabe todo de ti. También cuánto tiempo desperdicias.",
      "Estás envejeciendo ahora mismo, mientras lees esto.",
      "No recuerdas lo que hiciste ayer. Imagina en un año.",
      "La vida no está en pausa. Solo tú.",
      "Abriste esta app. Significa que lo sabes.",
      "Nadie te devolverá esta tarde.",
      "Estás esperando sentirte listo. No pasará.",
      "Hoy terminará. Como todos los otros días que desperdiciaste.",
      "Tomas tanto impulso que cuando tienes que partir ya estás muerto de cansancio. O solo muerto.",
      "Revisaste el teléfono 47 veces hoy. Nada importante.",
      "Tu lista de cosas por hacer es más vieja que tus sueños.",
      "Estás esperando el estado de ánimo correcto. Eso no es una estrategia.",
      "¿Cada notificación que abriste hoy valía tu tiempo?",
      "Pasas un año, más de un tercio durmiendo. Eres más activo cuando te despiertas.",
      "Tu cuerpo envejece incluso cuando no haces nada.",
      "Has postergado tanto que olvidaste lo que querías.",
      "No es pereza. Es miedo. Y eso es peor.",
      "En diez años recordarás este momento como tiempo perdido.",
      "Estás leyendo esto en vez de hacer esa cosa. Lo sabes.",
      "Tienes un sueño en un cajón. El cajón lleva años cerrado.",
      "No estás descansando. Solo estás postergando en posición horizontal.",
      "Dijiste después hoy. Después ya pasó.",
      "El tiempo que desperdiciaste hoy no volverá.",
      "Estás esperando que alguien te dé permiso. No llegará.",
      "Pensaste tanto en qué hacer que ahora que vas a hacerlo cambiaste de opinión.",
      "El día está terminando. Como todos los demás.",
      "Tu potencial está cansado de esperarte.",
      "Cada día es igual al anterior.",
      "Te consumes a ti mismo.",
      "Cada día igual al anterior es una elección.",
      "Qué triste la versión de ti en 5 años que esperaba grandes cosas. Pero nunca despertaste.",
      "Despierta y aprende a escuchar a quienes te hablan.",
      "Estás esperando la motivación. Ella te está esperando a ti.",
      "¿Viviste hoy o solo lo atravesaste?",
      "El problema no es el tiempo. Eres tú.",
      "Mañana empezará exactamente igual que hoy. A menos que hagas algo ahora.",
      "Estás coleccionando días vacíos.",
      "Tu vida no está en construcción. Está en curso. Ahora.",
      "Tienes tanto miedo a la espontaneidad que criticas a todos. Qué desperdicio.",
      "Riiiiiiiing. Despierta, que todavía estás durmiendo.",
      "Todo quiere vivir y tú no dejas que tu vitalidad se abra al mundo como una flor.",
      "Tienes un sueño. Solo olvidaste dónde lo pusiste.",
      "Estás haciendo scroll. Tu vida se desplaza con él.",
      "No postergaste una cosa. Te postergaste a ti mismo.",
      "Sigues donde estabas ayer. No es casualidad.",
      "¿Necesitas un descanso de qué, exactamente?",
      "Estás esperando ser feliz para empezar. Es al revés.",
      "No recordarás este momento. Ese es el problema.",
      "Tienes toda la vida por delante. ¿Estás usando bien esta parte?",
      "El silencio que escuchas es el tiempo que pasa.",
      "No es cansancio. Es distancia de ti mismo.",
      "¿Vives por hábito o por elección?",
      "¿Hiciste algo por primera vez hoy?",
      "No es demasiado tarde. Pero tampoco es temprano.",
      "Mientras esperas el momento perfecto que siempre está en el futuro, el momento perfecto pasa de ti y se toma una copa sin ti.",
      "¿Tienes miedo de empezar o de terminar?",
      "No es que no sepas qué hacer. Es que sabes lo que no estás haciendo.",
      "¿Cuántas versiones de ti has abandonado por el camino?",
      "No existe el día correcto. Solo existe este.",
      "Estás esperando sentirte mejor. El cuerpo no miente, la mente sí.",
      "Revisaste las redes sociales. Nada tuyo ha cambiado.",
      "¿Estás construyendo algo o solo mirando a otros construir?",
      "Cada minuto que pasa es un minuto que elegiste.",
      "No es culpa de nadie. Es más difícil aceptarlo así.",
      "Estás envejeciendo en tiempo real. También ahora.",
      "Has postergado tantas veces que postergar se ha convertido en quien eres.",
      "No necesitas más tiempo. Necesitas menos miedo.",
      "Estás esperando que algo cambie. Tú eres esa cosa.",
      "¿Hiciste algo que te asusta hoy?",
      "Tu futuro te está mirando. No parece satisfecho.",
      "No es una fase. Son años.",
      "Estás consumiendo tu vida mirando la de los demás.",
      "No perdiste el tiempo. Te perdiste a ti mismo en el tiempo.",
      "Estás despierto. No es lo mismo que estar presente.",
      "Tienes todo lo que necesitas. Excepto el coraje de usarlo.",
      "Estás esperando el permiso. No llegará por correo.",
      "No es que no puedas. Es que todavía no has decidido querer.",
      "Hoy terminará. ¿Qué dirás que hiciste?",
      "No estás descansando. Estás evitando.",
      "Tenías toda una vida por delante. Ahora tienes menos. Mañana aún menos. Muévete y despierta.",
      "Las alas crecen volando.",
      "Eres tan avaro con la vida que hasta el aburrimiento prefiere distraerse.",
      "¿Listo? Lázaro, levántate y camina.",
      "No es demasiado tarde para hoy. Pero hoy está terminando.",
      "No estás buscando el sentido. Estás buscando una excusa.",
      "Sigues aquí. Ya es algo. Pero no es suficiente.",
      "Tienes todo lo que necesitas menos una razón para no empezar ahora.",
      "FINITO.",
    ],};

  static String casuale(String lingua) {
    final lista = tutte[lingua] ?? tutte['english']!;
    return lista[Random().nextInt(lista.length)];
  }
}